### ISSUE TITLE
Thanks and a Suggestion

### ISSUE THREAD

**Issue by aolszowka** [bryanbraun/bryanbraun.github.io#36]
https://github.com/bryanbraun/bryanbraun.github.io/blob/master/_posts/2018-10-01-youth-group-activity-the-game-of-life.md

Was very helpful for an Activity Day; might I suggest uploading the source to its own repository to allow additional revisions?

**Comment by bryanbraun** [comment]
Yeah, good idea. The source files are [in this repo](https://github.com/bryanbraun/bryanbraun.github.io/blob/master/assets/documents/game-of-life.zip) but it's packaged as a zip file, which is pretty opaque.

A separate repo would work. It could also be nice to reformat the files as google docs, since that would probably be better for non-techy people and would let them easily read the docs, duplicate a copy, and share it with collaborators (though proposing changes upstream would be a bit trickier). I'm gonna keep thinking about this.
